name: release

on: 
  push:
    tags:
      - '*'

jobs:
  build-detours:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    strategy:
      matrix:
        arch:
          - vs_name: amd64
            detours_name: X64
          - vs_name: amd64_x86
            detours_name: X86
          - vs_name: amd64_arm
            detours_name: ARM
          - vs_name: amd64_arm64
            detours_name: ARM64

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch.vs_name }}
          sdk: 10.0.22621.0
          vsversion: 2022

      - name: Build detours (${{ matrix.arch.vs_name }})
        run: nmake
        working-directory: detours/src

      - name: Build the detours DLL (${{ matrix.arch.vs_name }})
        working-directory: detours-dll
        run: |
          mkdir bin
          pushd bin
          cl.exe /nologo /LD /TP /DUNICODE /DWIN32 /D_WINDOWS /EHsc /W4 /WX /Zi /O2 /Ob1 /DNDEBUG /Fodetours.obj /Fddetours.pdb ..\detours.cpp ^
              /link /def:..\detours.def "%GITHUB_WORKSPACE%\detours\lib.${{ matrix.arch.detours_name }}\detours.lib"
          popd

      - uses: actions/upload-artifact@main
        with:
          name: bin.${{ matrix.arch.detours_name }}
          path: detours-dll/bin
      
      - uses: actions/upload-artifact@main
        with:
          name: lib.${{ matrix.arch.detours_name }}
          path: detours/lib.${{ matrix.arch.detours_name }}

  
  build-and-publish-metadata:
    needs: build-detours
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
          submodules: true
      
      - uses: actions/download-artifact@main
        with:
          pattern: bin.*
          path: detours-dll

      - uses: actions/download-artifact@main
        with:
          pattern: lib.*
          path: detours

      - uses: actions/setup-dotnet@main
        with:
          dotnet-version: 10.0.x

      - run: |
          Invoke-WebRequest -OutFile Update-AssemblyInfoVersionFiles.ps1 https://gist.githubusercontent.com/lowleveldesign/663de4e0d5a071f938e6f7c82d7ca9a0/raw/Update-AssemblyInfoVersionFiles.ps1
          ./Update-AssemblyInfoVersionFiles.ps1
        shell: pwsh

      - name: Build detours metadata
        working-directory: package
        run: dotnet pack -c Release

      - run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k "$env:NUGET_KEY" Detours.Win32Metadata.*.nupkg
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        working-directory: package/bin/Release

      - uses: actions/upload-artifact@main
        with:
          name: Detours.winmd
          path: src/bin/Detours.winmd

      - uses: actions/upload-artifact@main
        with:
          name: Nuget package
          path: package/bin/Release/Detours.Win32Metadata.*.nupkg
